### ISSUE TITLE
Line numbers don't show up in code blocks

### ISSUE THREAD

**Issue by gsingh93** [Junyi-99/hugo-theme-anubis2#37]
If I enable `linenos` for a code block, the line numbers don't show up:
````markdown
```c {linenos=true,hl_lines=[1,"3-4"]}
int main() {
    int a;
    int b;
    int c;
}
```
````
How it looks:
<img width="769" alt="image" src="https://github.com/Junyi-99/hugo-theme-anubis2/assets/1012677/1b8ad1c1-170e-480d-939b-6372a5543bf5">

Checking the HTML shows that they're there, but the color matches the background. I tested with the "friendly" and "monokai" themes.

Only somewhat related, but I think there are extra borders being generated with `linenos=true` that don't look good by default, would be nice to have better styling here.

**Comment by gsingh93** [comment]
Interestingly, line numbers show up with this configuration in `config.toml`:
```
[markup.highlight]
noClasses = false
```
And then generating the styles with `hugo gen chromastyles`. But it still doesn't look great, could use some improved styling:
<img width="646" alt="image" src="https://github.com/Junyi-99/hugo-theme-anubis2/assets/1012677/1f1eaa37-bd60-4925-a0a9-de4372d6a7ae">

**Comment by Junyi-99** [comment]
Thank you for the explanation as I have not tested this before so I don't know if the number is not working.

I'll solve this when I have time.

**Comment by Junyi-99** [comment]
> Interestingly, line numbers show up with this configuration in `config.toml`:
> 
> ```
> [markup.highlight]
> noClasses = false
> ```
> 
> And then generating the styles with `hugo gen chromastyles`. But it still doesn't look great, could use some improved styling: <img alt="image" width="646" src="https://private-user-images.githubusercontent.com/1012677/323436918-1f1eaa37-bd60-4925-a0a9-de4372d6a7ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MTEwOTUsIm5iZiI6MTcxMzgxMDc5NSwicGF0aCI6Ii8xMDEyNjc3LzMyMzQzNjkxOC0xZjFlYWEzNy1iZDYwLTQ5MjUtYTBhOS1kZTQzNzJkNmE3YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjJUMTgzMzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDg1NDY4MmExNWRjZWViMDRmNmExMjA5NmIzYmZiM2Y0NmVlYzg2NmZjOTg0MGQ3NGQ0Y2E1NWU0MDkyYWI4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RKFefZxtLAVKufQdWqN4cLm5JuZePWSMMaBm2feBQtE">

If `markup.highlight.noClasses=false` is used in the site configuration, a stylesheet is required. However, there is a problem with the base style, so the provided stylesheet does not work.

**Comment by Junyi-99** [comment]
The branch [feat-experimental-config](https://github.com/Junyi-99/hugo-theme-anubis2/tree/feat-experimental-config) contains the latest fix, but it still need some test to be merged into main.

Here is the preview of the latest fix:
<img width="794" alt="image" src="https://github.com/Junyi-99/hugo-theme-anubis2/assets/14367694/89de566b-114d-4835-910f-6731cb294a15">

**Comment by Junyi-99** [comment]
the change has been merged.
