### ISSUE TITLE
index home page don't have footer

### ISSUE THREAD

**Issue by ChenYin626** [Junyi-99/hugo-theme-anubis2#40]
I am a hugo  newbie.I use your anubis2 exampleSiteMultilingual. I want to add icp and police message .But in the home page don't have footer. I saw your website https://www.junyi.dev/ have it.So,can you tell me how to fix or provide a simple configraution method in the config.yaml ?

**Comment by Junyi-99** [comment]
Hi Chenyin,

There is neither support for the customized footer nor the icp.

However, it's a great suggestion to add these two support for Anubis2.

**Comment by Junyi-99** [comment]
Now anubis supports ICP beian, please update to the latest version.

```bash
git submodule update --remote
```

The configuration is simple, just add `icp` inside `[params]` section.
https://github.com/Junyi-99/hugo-theme-anubis2/blob/3310c840fda576342e850b6fa6e24208e89a63d8/exampleSiteMultilingual/hugo.toml#L20

**Comment by ChenYin626** [comment]
hello,junyi,thank you for your code.I have  updated my code,and running in my windows computer.But it still have bug in the footer.
You can run your exampleSiteMultilingual.In the home page,doesn't have a footer
There are some pictures to show the bug.
![53e909ce67fa47c81130d30388931098](https://github.com/Junyi-99/hugo-theme-anubis2/assets/67036426/2e0fedf2-796b-4869-818d-3fe616dbc451)
but in other pages you can see the footer.
![35a15d5cee52a61d539b9f650ab50d4e](https://github.com/Junyi-99/hugo-theme-anubis2/assets/67036426/045313af-0608-47d6-822f-848a93b403cf)
I don't know how to fix it,and in your website it is fine.Please help me.

**Comment by Junyi-99** [comment]
I see, it's not a bug of Anubis but a bug of hugo. https://github.com/gohugoio/hugo/issues/12426#issue-2261951079

You should try to remove all `demo-summary-rendering-*.md` files, and it will back to normal.

**Comment by ChenYin626** [comment]
I remove that files.It is work.Thank you.

**Comment by Junyi-99** [comment]
ur welcome
